// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {main} from '../models';

export function Archive(arg1:number,arg2:boolean):Promise<void>;

export function CreateNoteFromLine(arg1:string):Promise<store.Todo>;

export function CreateTodoFromLine(arg1:string):Promise<store.Todo>;

export function DeleteTodo(arg1:number):Promise<void>;

export function ExportTodoTxt():Promise<string>;

export function GetBackrefs(arg1:number):Promise<Array<store.Todo>>;

export function GetDatabasePath():Promise<string>;

export function GetDefaultDatabasePath():Promise<string>;

export function GetFilters():Promise<main.FiltersResult>;

export function GetInboxCount():Promise<number>;

export function GetInboxItems(arg1:store.SearchRequest):Promise<Array<store.Todo>>;

export function GetTodo(arg1:number):Promise<store.Todo>;

export function HasDemoData():Promise<boolean>;

export function ImportTodoTxt(arg1:string):Promise<void>;

export function NeedsSetup():Promise<boolean>;

export function ProcessInboxItem(arg1:number):Promise<void>;

export function RemoveDemoData():Promise<void>;

export function Restart():Promise<void>;

export function Search(arg1:store.SearchRequest):Promise<Array<store.Todo>>;

export function SeedDemoData():Promise<void>;

export function SetDatabasePath(arg1:string):Promise<void>;

export function ToggleComplete(arg1:number,arg2:boolean):Promise<void>;

export function UpdateTodo(arg1:store.Todo):Promise<void>;
