// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function Archive(arg1:number,arg2:boolean):Promise<void>;

export function CreateTodoFromLine(arg1:string):Promise<store.Todo>;

export function DeleteTodo(arg1:number):Promise<void>;

export function GetFilters():Promise<Array<string>>;

export function Search(arg1:store.SearchRequest):Promise<Array<store.Todo>>;

export function ToggleComplete(arg1:number,arg2:boolean):Promise<void>;

export function UpdateTodo(arg1:store.Todo):Promise<void>;
