// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Archive(arg1, arg2) {
  return window['go']['main']['App']['Archive'](arg1, arg2);
}

export function CreateItemFromLine(arg1) {
  return window['go']['main']['App']['CreateItemFromLine'](arg1);
}

export function CreateNoteFromLine(arg1) {
  return window['go']['main']['App']['CreateNoteFromLine'](arg1);
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function ExportTodoTxt() {
  return window['go']['main']['App']['ExportTodoTxt']();
}

export function GetBackrefs(arg1) {
  return window['go']['main']['App']['GetBackrefs'](arg1);
}

export function GetDatabasePath() {
  return window['go']['main']['App']['GetDatabasePath']();
}

export function GetDefaultDatabasePath() {
  return window['go']['main']['App']['GetDefaultDatabasePath']();
}

export function GetFilters() {
  return window['go']['main']['App']['GetFilters']();
}

export function GetInboxCount() {
  return window['go']['main']['App']['GetInboxCount']();
}

export function GetInboxItems(arg1) {
  return window['go']['main']['App']['GetInboxItems'](arg1);
}

export function GetItem(arg1) {
  return window['go']['main']['App']['GetItem'](arg1);
}

export function HasDemoData() {
  return window['go']['main']['App']['HasDemoData']();
}

export function ImportTodoTxt(arg1) {
  return window['go']['main']['App']['ImportTodoTxt'](arg1);
}

export function NeedsSetup() {
  return window['go']['main']['App']['NeedsSetup']();
}

export function ProcessInboxItem(arg1) {
  return window['go']['main']['App']['ProcessInboxItem'](arg1);
}

export function RemoveDemoData() {
  return window['go']['main']['App']['RemoveDemoData']();
}

export function Restart() {
  return window['go']['main']['App']['Restart']();
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SeedDemoData() {
  return window['go']['main']['App']['SeedDemoData']();
}

export function SetDatabasePath(arg1) {
  return window['go']['main']['App']['SetDatabasePath'](arg1);
}

export function ToggleComplete(arg1, arg2) {
  return window['go']['main']['App']['ToggleComplete'](arg1, arg2);
}

export function UpdateItem(arg1) {
  return window['go']['main']['App']['UpdateItem'](arg1);
}
