// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {config} from '../models';
import {main} from '../models';

export function Archive(arg1:number,arg2:boolean):Promise<void>;

export function CreateItemFromLine(arg1:string):Promise<store.Item>;

export function CreateNoteFromLine(arg1:string):Promise<store.Item>;

export function CreateVault(arg1:string,arg2:string):Promise<config.Vault>;

export function DeleteItem(arg1:number):Promise<void>;

export function DeleteVault(arg1:string):Promise<void>;

export function ExportTodoTxt():Promise<string>;

export function GetAPIConfig():Promise<main.APIConfigResult>;

export function GetActiveVault():Promise<config.Vault>;

export function GetBackrefs(arg1:number):Promise<Array<store.Item>>;

export function GetDatabasePath():Promise<string>;

export function GetDefaultDatabasePath():Promise<string>;

export function GetFilters():Promise<main.FiltersResult>;

export function GetInboxCount():Promise<number>;

export function GetInboxItems(arg1:store.SearchRequest):Promise<Array<store.Item>>;

export function GetItem(arg1:number):Promise<store.Item>;

export function GetVaults():Promise<Array<config.Vault>>;

export function HasDemoData():Promise<boolean>;

export function ImportTodoTxt(arg1:string):Promise<void>;

export function NeedsSetup():Promise<boolean>;

export function ProcessInboxItem(arg1:number,arg2:string):Promise<void>;

export function RemoveDemoData():Promise<void>;

export function RenameVault(arg1:string,arg2:string):Promise<void>;

export function Restart():Promise<void>;

export function Search(arg1:store.SearchRequest):Promise<Array<store.Item>>;

export function SeedDemoData():Promise<void>;

export function SetAPIEnabled(arg1:boolean):Promise<void>;

export function SetDatabasePath(arg1:string):Promise<void>;

export function SwitchVault(arg1:string):Promise<config.Vault>;

export function ToggleComplete(arg1:number,arg2:boolean):Promise<void>;

export function UpdateItem(arg1:store.Item):Promise<void>;
