// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Archive(arg1, arg2) {
  return window['go']['main']['App']['Archive'](arg1, arg2);
}

export function CreateTodoFromLine(arg1) {
  return window['go']['main']['App']['CreateTodoFromLine'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['main']['App']['DeleteTodo'](arg1);
}

export function ExportTodoTxt() {
  return window['go']['main']['App']['ExportTodoTxt']();
}

export function GetFilters() {
  return window['go']['main']['App']['GetFilters']();
}

export function ImportTodoTxt(arg1) {
  return window['go']['main']['App']['ImportTodoTxt'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function ToggleComplete(arg1, arg2) {
  return window['go']['main']['App']['ToggleComplete'](arg1, arg2);
}

export function UpdateTodo(arg1) {
  return window['go']['main']['App']['UpdateTodo'](arg1);
}
