// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Archive(arg1, arg2) {
  return window['go']['main']['App']['Archive'](arg1, arg2);
}

export function CreateTodoFromLine(arg1) {
  return window['go']['main']['App']['CreateTodoFromLine'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['main']['App']['DeleteTodo'](arg1);
}

export function ExportTodoTxt() {
  return window['go']['main']['App']['ExportTodoTxt']();
}

export function GetDatabasePath() {
  return window['go']['main']['App']['GetDatabasePath']();
}

export function GetDefaultDatabasePath() {
  return window['go']['main']['App']['GetDefaultDatabasePath']();
}

export function GetFilters() {
  return window['go']['main']['App']['GetFilters']();
}

export function HasDemoData() {
  return window['go']['main']['App']['HasDemoData']();
}

export function ImportTodoTxt(arg1) {
  return window['go']['main']['App']['ImportTodoTxt'](arg1);
}

export function NeedsSetup() {
  return window['go']['main']['App']['NeedsSetup']();
}

export function RemoveDemoData() {
  return window['go']['main']['App']['RemoveDemoData']();
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SeedDemoData() {
  return window['go']['main']['App']['SeedDemoData']();
}

export function SetDatabasePath(arg1) {
  return window['go']['main']['App']['SetDatabasePath'](arg1);
}

export function ToggleComplete(arg1, arg2) {
  return window['go']['main']['App']['ToggleComplete'](arg1, arg2);
}

export function UpdateTodo(arg1) {
  return window['go']['main']['App']['UpdateTodo'](arg1);
}
